apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuto-shiny-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rcbrk/tuto_argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: tuto-shiny
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
