apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyY2hlYnJlayIsInBhc3N3b3JkIjoiTTByYkBrNjE5IiwiZW1haWwiOiJyb21haW4uY2hlYnJla0BnbWFpbC5jb20iLCJhdXRoIjoiY21Ob1pXSnlaV3M2VFRCeVlrQnJOakU1In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: tuto-shiny
  uid: a89cdc0e-fe8a-4dfb-a918-a0d52e5e256c
type: kubernetes.io/dockerconfigjson
